# Generated by Django 3.0.5 on 2020-04-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='_class',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.Class'),
        ),
    ]
